# Generated by Django 5.2.9 on 2026-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
    ]
